/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('vue-amazing-ui')['Avatar']
    BackTop: typeof import('vue-amazing-ui')['BackTop']
    Button: typeof import('vue-amazing-ui')['Button']
    Card: typeof import('vue-amazing-ui')['Card']
    Carousel: typeof import('vue-amazing-ui')['Carousel']
    Col: typeof import('vue-amazing-ui')['Col']
    Collapse: typeof import('vue-amazing-ui')['Collapse']
    Flex: typeof import('vue-amazing-ui')['Flex']
    InputSearch: typeof import('vue-amazing-ui')['InputSearch']
    List: typeof import('vue-amazing-ui')['List']
    ListItem: typeof import('vue-amazing-ui')['ListItem']
    Mylist: typeof import('./src/components/mylist.vue')['default']
    Myswiper: typeof import('./src/components/myswiper.vue')['default']
    Mytitle: typeof import('./src/components/mytitle.vue')['default']
    Radio: typeof import('vue-amazing-ui')['Radio']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('vue-amazing-ui')['Row']
    Scrollbar: typeof import('vue-amazing-ui')['Scrollbar']
    Select: typeof import('vue-amazing-ui')['Select']
    Space: typeof import('vue-amazing-ui')['Space']
    Steps: typeof import('vue-amazing-ui')['Steps']
  }
}
